ci| add meaningful error message on configure failure

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -42,7 +42,7 @@ jobs:
     - name: Configure
       run: |
         OPTS=${OPTS} ./docker/run_ci.sh '${DUNECONTROL} configure'
-    - name: Upload error logs in case of failure
+    - name: Upload error logs (on failure)
       if: ${{ failure() }}
       uses: actions/upload-artifact@v3
       with:
@@ -50,6 +50,16 @@ jobs:
         path: |
           /build/gcc-debug.ninja/dune-gdt/CMakeFiles/CMakeOutput.log
           /build/gcc-debug.ninja/dune-gdt/CMakeFiles/CMakeError.log
+    - name: Abort with meaningful error message (on failure)
+      if: ${{ failure() }}
+      run: |
+        echo "There was an error configuring (see above)!"
+        echo "To reproduce the failure locally, execute"
+        echo "    git clone https://github.com/dune-gdt/dune-gdt.git"
+        echo "    cd dune-gdt"
+        echo "    git checkout ${{ github.ref }}"
+        echo "    OPTS=${OPTS} ./docker/run_ci.sh '${DUNECONTROL} configure'"
+        exit 1
     - name: Check headers
       run: |
         OPTS=${OPTS} ./docker/run_ci.sh '${DUNECONTROL} dxt_headercheck'
